### PR TITLE
Example app with CAS-authenticated login

### PR DESCRIPTION
**Pull request by boutell**
This is a great module but when I picked it up I was pretty fuzzy on how to put it to work. The documentation is a little thin on those basics.

As a code sample for other CAS newcomers, I've submitted a tiny Express app that demonstrates a public homepage, a protected login URL that redirects back to the homepage, displaying the username on the homepage if logged in, and logging out correctly.

### CODE REVIEW

**Comment by KidkArolis** [comment]
Thanks! This was useful for implementing a /logout endpoint. +1 on merging this PR.

**Comment by madhusudhand** [comment]
Thanks for the example.
But I am missing the following scenario.

I logged into the app and logged out of CAS server from another tab.
In this case I expect my app to get logged out automatically. But it still logged-in even after refresh.
I again have to do a logout with in the app.

Could you please add this scenario as well in the example.
It really helps!!

Thanks,
Madhu

**Comment by boutell** [comment]
I'm not aware of such a feature. It would require constant polling of the
CAS server, or a push back from the CAS server to the application server. I
don't recall seeing any information about either feature in the CAS
specification although it has been a while.

On Thu, Feb 11, 2016 at 2:44 AM, Madhusudhan Dollu <notifications@github.com
> wrote:

> Thanks for the example.
> But I am missing the following scenario.
>
> I logged into the app and logged out of CAS server from another tab.
> In this case I expect my app to get logged out automatically. But it still
> logged-in even after refresh.
> I again have to do a logout with in the app.
>
> Could you please add this scenario as well in the example.
> It really helps!!
>
> Thanks,
> Madhu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AceMetrix/connect-cas/pull/29#issuecomment-182751193>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by badunk** [comment]
Actually, CAS does support logout.  It notifies from the CAS server to the application server as you suggested: https://jasig.github.io/cas/development/installation/Logout-Single-Signout.html

**Comment by boutell** [comment]
Great! I'm not sure this feature existed at the time I read the spec.

On Thu, Feb 11, 2016 at 2:50 PM, Duncan Wong <notifications@github.com>
wrote:

> Actually, CAS does support logout. It notifies from the CAS server to the
> application server as you suggested:
> https://jasig.github.io/cas/development/installation/Logout-Single-Signout.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AceMetrix/connect-cas/pull/29#issuecomment-183034819>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
I would accept a pull request to my pull request if you figure it out (:

**Comment by badunk** [comment]
@madhusudhand Unfortunately, the logout middleware that is implemented right now may not necessarily be working.  It was written according to their spec at the time, but was ultimately untested.  It may take some time for me to test that now as I don't have access to a CAS server readily available.

Please write a separate issue for that, if you discover the root cause, I'll be happy to accept a PR.

**Comment by boutell** [comment]
Hooray!

How every pull request feels: https://www.youtube.com/watch?v=tyeJ55o3El0

**Pull request merged**
