### PR TITLE
Handle CAS user attributes pushed by the new /p3 (CAS protocol v3) endpoint

### PR DESCRIPTION
**Pull request by leleuj**

### CODE REVIEW

**Comment by badunk** [comment]
Hi thanks!

I'm not quite sure how adding the variable in your PR does anything.  The new variable isn't referenced after being assigned.

**Comment by leleuj** [comment]
It's a bit tricky, but the loop here: https://github.com/AceMetrix/connect-cas/blob/master/lib/service-validate.js#L111 iterates over the elements and populates ```req.session.cas.user``` and ```req.session.cas.attributes```. Finally, you can use this new property: ```req.session.cas.attributes``` (example: https://github.com/casinthecloud/nodejs-cas-client-demo/blob/master/routes/default.js#L15) to get the user attributes.
This works only if you use the new /p3 endpoint: https://github.com/casinthecloud/nodejs-cas-client-demo/blob/master/app.js#L13.

**Comment by badunk** [comment]
Thanks for the clarification - I was able to find the spec for the /p3 endpoint.

Maybe I'm misunderstanding, but your PR adds a single line (https://github.com/AceMetrix/connect-cas/pull/33/files#diff-e1be081a8393c4eeb59c9cf96f2745afR92) for variable assignment.

As I understand, the loop in https://github.com/AceMetrix/connect-cas/blob/master/lib/service-validate.js#L111 should pick up the new `success.attributes` anyways and save it in `req.session.cas.attributes`.  Adding the variable assignment should have no effect I'm guessing?

**Comment by leleuj** [comment]
You're right. It already works without my addon. Sorry for the misleading proposal.

CAS protocol v3 is already supported. At least, you know that now ;-) Thanks.

**Comment by badunk** [comment]
Thanks :)

**Pull request closed without merging**
